---
- name: Metabase DB setup
  hosts: dbs
  become: yes
  tags: metabase
  tasks:
    - name: Ensure MySQL service is started and enabled
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Create Metabase database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root

    - name: Create Metabase user for localhost
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        host: "localhost"
        priv: "{{ db_name }}.*:ALL"
        state: present
        login_user: root

    - name: Create Metabase user for any host (%)
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        host: "%"
        priv: "{{ db_name }}.*:ALL"
        state: present
        login_user: root

    - name: Alter user to use mysql_native_password (localhost)
      mysql_user:
        name: "{{ db_user }}"
        host: "localhost"
        password: "{{ db_password }}"
        login_user: root
        plugin: mysql_native_password
        state: present
        update_password: always

    - name: Alter user to use mysql_native_password (%)
      mysql_user:
        name: "{{ db_user }}"
        host: "%"
        password: "{{ db_password }}"
        login_user: root
        plugin: mysql_native_password
        state: present
        update_password: always

    - name: Flush privileges
      shell: "mysql -u root -e 'FLUSH PRIVILEGES;'"
      args:
        executable: /bin/bash

- name: Metabase runtime installation
  hosts: runtime
  become: yes
  tags: metabase
  tasks:
    - name: Install Java for Metabase
      apt:
        name: openjdk-11-jre-headless
        state: present

    - name: Create Metabase directory
      file:
        path: /opt/metabase
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Download Metabase JAR
      get_url:
        url: https://downloads.metabase.com/v0.48.7/metabase.jar
        dest: /opt/metabase/metabase.jar
        mode: '0755'

    - name: Create Metabase systemd service file
      copy:
        dest: /etc/systemd/system/metabase.service
        content: |
          [Unit]
          Description=Metabase server
          After=network.target

          [Service]
          WorkingDirectory=/opt/metabase
          ExecStart=/usr/bin/java -jar /opt/metabase/metabase.jar
          Restart=always
          RestartSec=10
          User=root

          [Install]
          WantedBy=multi-user.target
      notify: Restart Metabase

    - name: Start and enable Metabase service
      systemd:
        name: metabase
        state: started
        enabled: yes

  # handlers:
  #   - name: Restart Metabase
  #     systemd:
  #       name: metabase
  #       state: restarted
